<a href="https://colab.research.google.com/github/Rupesh-Kataria/Data-Science-By-CodeBasics/blob/main/Part26(K_Fold_Validation).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [61]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)

In [62]:
lr=LogisticRegression(max_iter=10000)
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

0.9611111111111111

In [63]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9851851851851852

In [64]:
rf=RandomForestClassifier(n_estimators=40)
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9685185185185186

In [65]:
#the performance of the every model changes after every run because of varying of training and test data
#So running one time and saying that particular model is better is not right thing
#So we use k fold api to demonstrate
from sklearn.model_selection import KFold
kf=KFold(n_splits=4)#here you can specify how much fold do you want to create
kf

KFold(n_splits=4, random_state=None, shuffle=False)

In [66]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 5 6 7 8] [3 4]
[0 1 2 3 4 7 8] [5 6]
[0 1 2 3 4 5 6] [7 8]


In [67]:
def get_score(model,X_train,X_test,y_train,y_test):    #this method is used to calculate score like above but we do not need to write it again and again
     model.fit(X_train,y_train)
     return model.score(X_test,y_test)

In [68]:
get_score(SVC(),X_train,X_test,y_train,y_test)

0.9851851851851852

In [69]:
#stratifiedKFold is same as k FOLD but it is better out when we you sepaarating the fold it will divide each of the classification categorically in uniform way
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [80]:
scores_l=[]    #scores of logistic regression
scores_svm=[]
scores_rf=[]
for train_index,test_index in kf.split(digits.data):
     X_train,X_test,y_train,y_test= digits.data[train_index],digits.data[test_index], digits.target[train_index],digits.target[test_index]
     scores_l.append(get_score(LogisticRegression(max_iter=10000),X_train,X_test,y_train,y_test))
     scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
     scores_rf.append(get_score(RandomForestClassifier(n_estimators=40),X_train,X_test,y_train,y_test))


In [81]:
scores_l

[0.9355555555555556, 0.9242761692650334, 0.955456570155902, 0.9198218262806236]

In [83]:
scores_svm

[0.9644444444444444,
 0.9665924276169265,
 0.9821826280623608,
 0.9487750556792873]

In [84]:
scores_rf

[0.9311111111111111,
 0.9153674832962138,
 0.9510022271714922,
 0.9287305122494433]

In [86]:
#Baed on the above we can see svm is better
#We can also do the above thing using cross_val_scores
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(max_iter=10000),digits.data,digits.target)

array([0.925     , 0.87777778, 0.93871866, 0.93314763, 0.89693593])

In [88]:
cross_val_score(SVC(),digits.data,digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [89]:
cross_val_score(RandomForestClassifier(n_estimators=5),digits.data,digits.target) #we can compare same classifier  with different parameter that is parameter tunning 
#cross_validation technique is useful it allow you to compare different classifier and same classifier also with different parameter 

array([0.82777778, 0.78611111, 0.87743733, 0.87743733, 0.86350975])

In [90]:
cross_val_score(RandomForestClassifier(n_estimators=15),digits.data,digits.target)

array([0.91111111, 0.87222222, 0.92200557, 0.9275766 , 0.89693593])