<a href="https://colab.research.google.com/github/Rupesh-Kataria/Data-Science-By-CodeBasics/blob/main/Part18(Pickle_and_joblib).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [81]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [82]:
df=pd.read_csv("https://raw.githubusercontent.com/codebasics/py/master/ML/1_linear_reg/homeprices.csv")
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [83]:
model=linear_model.LinearRegression() #creating object of linear model
model.fit(df[['area']],df.price)

LinearRegression()

In [84]:
model.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

In [85]:
model.coef_       

array([135.78767123])

In [86]:
model.intercept_  

180616.43835616432

In [87]:
import pickle  #python pickle module used to serialise the python object into a file

In [88]:
with open('model_pickle','wb') as f:        #since I am writting binary data so i used wb mode in file
      pickle.dump(model,f)                  #dump my model into this file
#when i run this it create a model_pickle file in my working directory

In [89]:
#Now our model is saved in binary file that is model_pickle .Now we can used this model
with open('model_pickle','rb') as f:
      mp=pickle.load(f)         #Now I have my model loaded from a file into the memory and mp is the object

In [90]:
#Now if i have to use my object for prediction
mp.predict([[5000]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([859554.79452055])

## There is a second approach of saving a model into file using sklearn joblib  
Note we can share our model file to our friend so that he can find model prediction

##If your model contain large numpy array then it is better to use joblib

In [91]:
# import sklearn
# from sklearn.externals import joblib

In [92]:
#the difference between pickle api and joblib api is that joblib api take file name directly
#joblib.dump(model,'model_joblib')    #our model is successfully saved in a file

In [93]:
#mj=joblib.load('model_joblib')
#mj.predict([[5000]])
#mj.predict([[5000]])
#mj.coef_
#mj.intercept_